// <auto-generated />
using HamsterWars.Server.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(HamsterDBContext))]
    partial class HamsterDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HamsterWars.Shared.Models.Hamster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FavFood")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Games")
                        .HasColumnType("int");

                    b.Property<string>("ImgName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Losses")
                        .HasColumnType("int");

                    b.Property<string>("Loves")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hamsters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 4,
                            FavFood = "Cheese",
                            Games = 0,
                            ImgName = "hamster-1.jpg",
                            Losses = 0,
                            Loves = "Ball",
                            Name = "McFuzz",
                            Wins = 0
                        },
                        new
                        {
                            Id = 2,
                            Age = 50,
                            FavFood = "Meatballs",
                            Games = 0,
                            ImgName = "hamster-2.jpg",
                            Losses = 0,
                            Loves = "Running wheel",
                            Name = "Karin",
                            Wins = 0
                        },
                        new
                        {
                            Id = 3,
                            Age = 11,
                            FavFood = "Pizza",
                            Games = 0,
                            ImgName = "hamster-3.jpg",
                            Losses = 0,
                            Loves = "Nothing",
                            Name = "Nicolas",
                            Wins = 0
                        },
                        new
                        {
                            Id = 4,
                            Age = 105,
                            FavFood = "Burrito",
                            Games = 0,
                            ImgName = "hamster-4.jpg",
                            Losses = 0,
                            Loves = "Dancing",
                            Name = "Pedro",
                            Wins = 0
                        },
                        new
                        {
                            Id = 5,
                            Age = 2,
                            FavFood = "Pancakes",
                            Games = 0,
                            ImgName = "hamster-5.jpg",
                            Losses = 0,
                            Loves = "Pancakes",
                            Name = "Pancake",
                            Wins = 0
                        },
                        new
                        {
                            Id = 6,
                            Age = 6,
                            FavFood = "Cables",
                            Games = 0,
                            ImgName = "hamster-6.jpg",
                            Losses = 0,
                            Loves = "Electricity",
                            Name = "Carl",
                            Wins = 0
                        },
                        new
                        {
                            Id = 7,
                            Age = 59,
                            FavFood = "Bananas",
                            Games = 0,
                            ImgName = "hamster-7.jpg",
                            Losses = 0,
                            Loves = "Running around",
                            Name = "Mike",
                            Wins = 0
                        },
                        new
                        {
                            Id = 8,
                            Age = 5000,
                            FavFood = "Magic Rabbits",
                            Games = 0,
                            ImgName = "hamster-8.jpg",
                            Losses = 0,
                            Loves = "Magic",
                            Name = "Wizard",
                            Wins = 0
                        },
                        new
                        {
                            Id = 9,
                            Age = 30,
                            FavFood = "Coffee",
                            Games = 0,
                            ImgName = "hamster-9.jpg",
                            Losses = 0,
                            Loves = "Sauna",
                            Name = "Jorma",
                            Wins = 0
                        },
                        new
                        {
                            Id = 10,
                            Age = 9,
                            FavFood = "Sausage",
                            Games = 0,
                            ImgName = "hamster-10.jpg",
                            Losses = 0,
                            Loves = "Who knows",
                            Name = "Codey",
                            Wins = 0
                        },
                        new
                        {
                            Id = 11,
                            Age = 1,
                            FavFood = "Tamato",
                            Games = 0,
                            ImgName = "hamster-11.jpg",
                            Losses = 0,
                            Loves = "Friends",
                            Name = "Togepi",
                            Wins = 0
                        },
                        new
                        {
                            Id = 12,
                            Age = 13,
                            FavFood = "Beans",
                            Games = 0,
                            ImgName = "hamster-12.jpg",
                            Losses = 0,
                            Loves = "Sleeping",
                            Name = "Poopers",
                            Wins = 0
                        },
                        new
                        {
                            Id = 13,
                            Age = 20,
                            FavFood = "Pineapple",
                            Games = 0,
                            ImgName = "hamster-13.jpg",
                            Losses = 0,
                            Loves = "Kama Sutra",
                            Name = "Kyle",
                            Wins = 0
                        },
                        new
                        {
                            Id = 14,
                            Age = 666,
                            FavFood = "Human leftovers",
                            Games = 0,
                            ImgName = "hamster-14.jpg",
                            Losses = 0,
                            Loves = "Playing with Demons",
                            Name = "Pog",
                            Wins = 0
                        },
                        new
                        {
                            Id = 15,
                            Age = 21,
                            FavFood = "Beer",
                            Games = 0,
                            ImgName = "hamster-15.jpg",
                            Losses = 0,
                            Loves = "Music",
                            Name = "DJ",
                            Wins = 0
                        },
                        new
                        {
                            Id = 16,
                            Age = 4,
                            FavFood = "Soup",
                            Games = 0,
                            ImgName = "hamster-16.jpg",
                            Losses = 0,
                            Loves = "Sleeping",
                            Name = "Blanket",
                            Wins = 0
                        },
                        new
                        {
                            Id = 17,
                            Age = 12,
                            FavFood = "...",
                            Games = 0,
                            ImgName = "hamster-17.jpg",
                            Losses = 0,
                            Loves = "Who's Asking?",
                            Name = "Paranoia",
                            Wins = 0
                        },
                        new
                        {
                            Id = 18,
                            Age = 30,
                            FavFood = "COINS",
                            Games = 0,
                            ImgName = "hamster-18.jpg",
                            Losses = 0,
                            Loves = "CHESTS",
                            Name = "Pirate",
                            Wins = 0
                        },
                        new
                        {
                            Id = 19,
                            Age = 4,
                            FavFood = "Cheeseballs",
                            Games = 0,
                            ImgName = "hamster-19.jpg",
                            Losses = 0,
                            Loves = "Cat",
                            Name = "Green",
                            Wins = 0
                        },
                        new
                        {
                            Id = 20,
                            Age = 420,
                            FavFood = "Dutch stuff",
                            Games = 0,
                            ImgName = "hamster-20.jpg",
                            Losses = 0,
                            Loves = "Blowing clouds",
                            Name = "Snoop",
                            Wins = 0
                        },
                        new
                        {
                            Id = 21,
                            Age = 3,
                            FavFood = "Wheat",
                            Games = 0,
                            ImgName = "hamster-21.jpg",
                            Losses = 0,
                            Loves = "Playing with rats",
                            Name = "Dave",
                            Wins = 0
                        },
                        new
                        {
                            Id = 22,
                            Age = 5,
                            FavFood = "Candy",
                            Games = 0,
                            ImgName = "hamster-22.jpg",
                            Losses = 0,
                            Loves = "RACING",
                            Name = "McQueen",
                            Wins = 0
                        },
                        new
                        {
                            Id = 23,
                            Age = 8,
                            FavFood = "Twinkies",
                            Games = 0,
                            ImgName = "hamster-23.jpg",
                            Losses = 0,
                            Loves = "Eat,Sleep,Twinkies,Repeat",
                            Name = "Chuck",
                            Wins = 0
                        },
                        new
                        {
                            Id = 24,
                            Age = 5,
                            FavFood = "Grass",
                            Games = 0,
                            ImgName = "hamster-24.jpg",
                            Losses = 0,
                            Loves = "Hide under beds",
                            Name = "Soda",
                            Wins = 0
                        },
                        new
                        {
                            Id = 25,
                            Age = 0,
                            FavFood = "?",
                            Games = 0,
                            ImgName = "hamster-25.jpg",
                            Losses = 0,
                            Loves = "?",
                            Name = "Questionmark",
                            Wins = 0
                        },
                        new
                        {
                            Id = 26,
                            Age = 1,
                            FavFood = "Hamstermilk",
                            Games = 0,
                            ImgName = "hamster-26.jpg",
                            Losses = 0,
                            Loves = "Hamster Wheel!!!!!",
                            Name = "Milk",
                            Wins = 0
                        },
                        new
                        {
                            Id = 27,
                            Age = 40,
                            FavFood = "Marshmellows",
                            Games = 0,
                            ImgName = "hamster-27.jpg",
                            Losses = 0,
                            Loves = "Playing with my bro's",
                            Name = "Boy",
                            Wins = 0
                        },
                        new
                        {
                            Id = 28,
                            Age = 40,
                            FavFood = "Marshmellows",
                            Games = 0,
                            ImgName = "hamster-28.jpg",
                            Losses = 0,
                            Loves = "Playin with my bro's",
                            Name = "Kid",
                            Wins = 0
                        },
                        new
                        {
                            Id = 29,
                            Age = 3,
                            FavFood = "Acid",
                            Games = 0,
                            ImgName = "hamster-29.jpg",
                            Losses = 0,
                            Loves = "Experimenting",
                            Name = "Chemical",
                            Wins = 0
                        },
                        new
                        {
                            Id = 30,
                            Age = 0,
                            FavFood = "Poop",
                            Games = 0,
                            ImgName = "hamster-30.jpg",
                            Losses = 0,
                            Loves = "Driving my owners to madness",
                            Name = "Little shit",
                            Wins = 0
                        },
                        new
                        {
                            Id = 31,
                            Age = 9,
                            FavFood = "Everything",
                            Games = 0,
                            ImgName = "hamster-31.jpg",
                            Losses = 0,
                            Loves = "Everything that entertains",
                            Name = "Milo",
                            Wins = 0
                        },
                        new
                        {
                            Id = 32,
                            Age = 40,
                            FavFood = "Pancakes",
                            Games = 0,
                            ImgName = "hamster-32.jpg",
                            Losses = 0,
                            Loves = "Playing guitar",
                            Name = "Lobba",
                            Wins = 0
                        },
                        new
                        {
                            Id = 33,
                            Age = 6000,
                            FavFood = "Sausages",
                            Games = 0,
                            ImgName = "hamster-33.jpg",
                            Losses = 0,
                            Loves = "Breeding magical creatures",
                            Name = "Swagrid",
                            Wins = 0
                        },
                        new
                        {
                            Id = 34,
                            Age = 1,
                            FavFood = "Ham",
                            Games = 0,
                            ImgName = "hamster-34.jpg",
                            Losses = 0,
                            Loves = "Going ham",
                            Name = "Mark",
                            Wins = 0
                        },
                        new
                        {
                            Id = 35,
                            Age = 12,
                            FavFood = "Carrots",
                            Games = 0,
                            ImgName = "hamster-35.jpg",
                            Losses = 0,
                            Loves = "Running",
                            Name = "Sunny",
                            Wins = 0
                        },
                        new
                        {
                            Id = 36,
                            Age = 5,
                            FavFood = "Paper",
                            Games = 0,
                            ImgName = "hamster-36.jpg",
                            Losses = 0,
                            Loves = "Sleeping",
                            Name = "Ash",
                            Wins = 0
                        },
                        new
                        {
                            Id = 37,
                            Age = 6000,
                            FavFood = "Sausages",
                            Games = 0,
                            ImgName = "hamster-37.jpg",
                            Losses = 0,
                            Loves = "Breeding magical creatures",
                            Name = "Swagrid",
                            Wins = 0
                        },
                        new
                        {
                            Id = 38,
                            Age = 2,
                            FavFood = "Meat",
                            Games = 0,
                            ImgName = "hamster-38.jpg",
                            Losses = 0,
                            Loves = "Reading books",
                            Name = "Alfons",
                            Wins = 0
                        },
                        new
                        {
                            Id = 39,
                            Age = 30,
                            FavFood = "Chicken",
                            Games = 0,
                            ImgName = "hamster-39.jpg",
                            Losses = 0,
                            Loves = "Racing",
                            Name = "Tetris",
                            Wins = 0
                        },
                        new
                        {
                            Id = 40,
                            Age = 3,
                            FavFood = "Cheese",
                            Games = 0,
                            ImgName = "hamster-40.jpg",
                            Losses = 0,
                            Loves = "Working out",
                            Name = "Pepsi",
                            Wins = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
